/* Automatically generated by './build/bin/build-entry.js' */

import CountDown from '../packages/count-down/index.js';
import JDictSelectTag from '../packages/j-dict-select-tag/index.js';
import JMultiSelectTag from '../packages/j-multi-select-tag/index.js';
import JSearchSelectTag from '../packages/j-search-select-tag/index.js';
import Ellipsis from '../packages/ellipsis/index.js';
import Jeecg from '../packages/jeecg/index.js';
import Jeecgbiz from '../packages/jeecgbiz/index.js';
import Table from '../packages/table/index.js';
import Tools from '../packages/tools/index.js';
import JVxeFileCell from '../packages/j-vxe-file-cell/index.js';
import JVxeImageCell from '../packages/j-vxe-image-cell/index.js';
import JVxePopupCell from '../packages/j-vxe-popup-cell/index.js';
import JVxeRadioCell from '../packages/j-vxe-radio-cell/index.js';
import JVxeSelectSearchSpanCell from '../packages/j-vxe-select-search-span-cell/index.js';
import JVxeSelectSearchInputCell from '../packages/j-vxe-select-search-input-cell/index.js';
import JVxeDetailsModal from '../packages/j-vxe-details-modal/index.js';
import JVxePagination from '../packages/j-vxe-pagination/index.js';
import JVxeSubPopover from '../packages/j-vxe-sub-popover/index.js';
import JVxeToolbar from '../packages/j-vxe-toolbar/index.js';
import ReloadEffect from '../packages/reload-effect/index.js';
import JAreaLinkage from '../packages/j-area-linkage/index.js';
import JCategorySelect from '../packages/j-category-select/index.js';
import JCheckbox from '../packages/j-checkbox/index.js';
import JCodeEditor from '../packages/j-code-editor/index.js';
import JCron from '../packages/j-cron/index.js';
import JDate from '../packages/j-date/index.js';
import JEditableTable from '../packages/j-editable-table/index.js';
import JEditor from '../packages/j-editor/index.js';
import JEllipsis from '../packages/j-ellipsis/index.js';
import JFormContainer from '../packages/j-form-container/index.js';
import JImageUpload from '../packages/j-image-upload/index.js';
import JImportModal from '../packages/j-import-modal/index.js';
import JInput from '../packages/j-input/index.js';
import JMarkdownEditor from '../packages/j-markdown-editor/index.js';
import JModal from '../packages/j-modal/index.js';
import JPopup from '../packages/j-popup/index.js';
import JSelectMultiple from '../packages/j-select-multiple/index.js';
import JSlider from '../packages/j-slider/index.js';
import JSuperQuery from '../packages/j-super-query/index.js';
import JSwitch from '../packages/j-switch/index.js';
import JTime from '../packages/j-time/index.js';
import JTreeDict from '../packages/j-tree-dict/index.js';
import JTreeSelect from '../packages/j-tree-select/index.js';
import JTreeTable from '../packages/j-tree-table/index.js';
import JUpload from '../packages/j-upload/index.js';
import JEditorDyn from '../packages/j-editor-dyn/index.js';
import JMdEditorDyn from '../packages/j-md-editor-dyn/index.js';
import JSqlCodeEditorDyn from '../packages/j-sql-code-editor-dyn/index.js';
import JsCodeEditorDyn from '../packages/js-code-editor-dyn/index.js';
import JFilePop from '../packages/j-file-pop/index.js';
import JInputPop from '../packages/j-input-pop/index.js';
import JCronModal from '../packages/j-cron-modal/index.js';
import JPopupOnlReport from '../packages/j-popup-onl-report/index.js';
import JSelectDepart from '../packages/j-select-depart/index.js';
import JSelectMultiUser from '../packages/j-select-multi-user/index.js';
import JSelectPosition from '../packages/j-select-position/index.js';
import JSelectRole from '../packages/j-select-role/index.js';
import JSelectUserByDep from '../packages/j-select-user-by-dep/index.js';
import JSelectDepartModal from '../packages/j-select-depart-modal/index.js';
import JSelectUserByDepModal from '../packages/j-select-user-by-dep-modal/index.js';
import SelectUserListModal from '../packages/select-user-list-modal/index.js';
import JSelectBizComponent from '../packages/j-select-biz-component/index.js';
import StandardTable from '../packages/standard-table/index.js';
import Breadcrumb from '../packages/breadcrumb/index.js';
import FooterToolBar from '../packages/footer-tool-bar/index.js';
import HeadInfo from '../packages/head-info/index.js';
import TwoStepCaptcha from '../packages/two-step-captcha/index.js';
import VerifyCode from '../packages/verify-code/index.js';
import CubeSelectEnum from '../packages/cube-select-enum/index.js';
import CubeIcon from '../packages/cube-icon/index.js';

const components = [
  CountDown,
  JDictSelectTag,
  JMultiSelectTag,
  JSearchSelectTag,
  Ellipsis,
  Jeecg,
  Jeecgbiz,
  Table,
  Tools,
  JVxeFileCell,
  JVxeImageCell,
  JVxePopupCell,
  JVxeRadioCell,
  JVxeSelectSearchSpanCell,
  JVxeSelectSearchInputCell,
  JVxeDetailsModal,
  JVxePagination,
  JVxeSubPopover,
  JVxeToolbar,
  ReloadEffect,
  JAreaLinkage,
  JCategorySelect,
  JCheckbox,
  JCodeEditor,
  JCron,
  JDate,
  JEditableTable,
  JEditor,
  JEllipsis,
  JFormContainer,
  JImageUpload,
  JImportModal,
  JInput,
  JMarkdownEditor,
  JModal,
  JPopup,
  JSelectMultiple,
  JSlider,
  JSuperQuery,
  JSwitch,
  JTime,
  JTreeDict,
  JTreeSelect,
  JTreeTable,
  JUpload,
  JEditorDyn,
  JMdEditorDyn,
  JSqlCodeEditorDyn,
  JsCodeEditorDyn,
  JFilePop,
  JInputPop,
  JCronModal,
  JPopupOnlReport,
  JSelectDepart,
  JSelectMultiUser,
  JSelectPosition,
  JSelectRole,
  JSelectUserByDep,
  JSelectDepartModal,
  JSelectUserByDepModal,
  SelectUserListModal,
  JSelectBizComponent,
  StandardTable,
  Breadcrumb,
  FooterToolBar,
  HeadInfo,
  TwoStepCaptcha,
  VerifyCode,
  CubeSelectEnum,
  CubeIcon,
];

const install = function(Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export {
  CountDown,
  JDictSelectTag,
  JMultiSelectTag,
  JSearchSelectTag,
  Ellipsis,
  Jeecg,
  Jeecgbiz,
  Table,
  Tools,
  JVxeFileCell,
  JVxeImageCell,
  JVxePopupCell,
  JVxeRadioCell,
  JVxeSelectSearchSpanCell,
  JVxeSelectSearchInputCell,
  JVxeDetailsModal,
  JVxePagination,
  JVxeSubPopover,
  JVxeToolbar,
  ReloadEffect,
  JAreaLinkage,
  JCategorySelect,
  JCheckbox,
  JCodeEditor,
  JCron,
  JDate,
  JEditableTable,
  JEditor,
  JEllipsis,
  JFormContainer,
  JImageUpload,
  JImportModal,
  JInput,
  JMarkdownEditor,
  JModal,
  JPopup,
  JSelectMultiple,
  JSlider,
  JSuperQuery,
  JSwitch,
  JTime,
  JTreeDict,
  JTreeSelect,
  JTreeTable,
  JUpload,
  JEditorDyn,
  JMdEditorDyn,
  JSqlCodeEditorDyn,
  JsCodeEditorDyn,
  JFilePop,
  JInputPop,
  JCronModal,
  JPopupOnlReport,
  JSelectDepart,
  JSelectMultiUser,
  JSelectPosition,
  JSelectRole,
  JSelectUserByDep,
  JSelectDepartModal,
  JSelectUserByDepModal,
  SelectUserListModal,
  JSelectBizComponent,
  StandardTable,
  Breadcrumb,
  FooterToolBar,
  HeadInfo,
  TwoStepCaptcha,
  VerifyCode,
  CubeSelectEnum,
  CubeIcon
}

export default {
  install,
  CountDown,
  JDictSelectTag,
  JMultiSelectTag,
  JSearchSelectTag,
  Ellipsis,
  Jeecg,
  Jeecgbiz,
  Table,
  Tools,
  JVxeFileCell,
  JVxeImageCell,
  JVxePopupCell,
  JVxeRadioCell,
  JVxeSelectSearchSpanCell,
  JVxeSelectSearchInputCell,
  JVxeDetailsModal,
  JVxePagination,
  JVxeSubPopover,
  JVxeToolbar,
  ReloadEffect,
  JAreaLinkage,
  JCategorySelect,
  JCheckbox,
  JCodeEditor,
  JCron,
  JDate,
  JEditableTable,
  JEditor,
  JEllipsis,
  JFormContainer,
  JImageUpload,
  JImportModal,
  JInput,
  JMarkdownEditor,
  JModal,
  JPopup,
  JSelectMultiple,
  JSlider,
  JSuperQuery,
  JSwitch,
  JTime,
  JTreeDict,
  JTreeSelect,
  JTreeTable,
  JUpload,
  JEditorDyn,
  JMdEditorDyn,
  JSqlCodeEditorDyn,
  JsCodeEditorDyn,
  JFilePop,
  JInputPop,
  JCronModal,
  JPopupOnlReport,
  JSelectDepart,
  JSelectMultiUser,
  JSelectPosition,
  JSelectRole,
  JSelectUserByDep,
  JSelectDepartModal,
  JSelectUserByDepModal,
  SelectUserListModal,
  JSelectBizComponent,
  StandardTable,
  Breadcrumb,
  FooterToolBar,
  HeadInfo,
  TwoStepCaptcha,
  VerifyCode,
  CubeSelectEnum,
  CubeIcon
};
